/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/

'use strict';

var obsidian = require('obsidian');

// Obsidian stores its display-language preference in localStorage. Keep the
// translations in this bundle so the plugin has no runtime dependency on a
// particular Obsidian translation API.
const TRANSLATIONS = {
    en: {
        none: "None",
        changeTheme: "Change theme",
        openThemePicker: "Open theme picker",
        switchToLightMode: "Switch to light mode",
        switchToDarkMode: "Switch to dark mode"
    },
    ja: {
        none: "なし",
        changeTheme: "テーマを変更",
        openThemePicker: "テーマピッカーを開く",
        switchToLightMode: "ライトモードに切り替え",
        switchToDarkMode: "ダークモードに切り替え"
    },
    fr: {
        none: "Aucun",
        changeTheme: "Changer de thème",
        openThemePicker: "Ouvrir le sélecteur de thème",
        switchToLightMode: "Passer en mode clair",
        switchToDarkMode: "Passer en mode sombre"
    },
    es: {
        none: "Ninguno",
        changeTheme: "Cambiar tema",
        openThemePicker: "Abrir selector de temas",
        switchToLightMode: "Cambiar al modo claro",
        switchToDarkMode: "Cambiar al modo oscuro"
    },
    de: {
        none: "Keines",
        changeTheme: "Thema ändern",
        openThemePicker: "Theme-Auswahl öffnen",
        switchToLightMode: "Zum hellen Modus wechseln",
        switchToDarkMode: "Zum dunklen Modus wechseln"
    },
    nl: {
        none: "Geen",
        changeTheme: "Thema wijzigen",
        openThemePicker: "Themakiezer openen",
        switchToLightMode: "Naar lichte modus schakelen",
        switchToDarkMode: "Naar donkere modus schakelen"
    },
    sv: {
        none: "Ingen",
        changeTheme: "Byt tema",
        openThemePicker: "Öppna temaväljaren",
        switchToLightMode: "Växla till ljust läge",
        switchToDarkMode: "Växla till mörkt läge"
    },
    ko: {
        none: "없음",
        changeTheme: "테마 변경",
        openThemePicker: "테마 선택기 열기",
        switchToLightMode: "라이트 모드로 전환",
        switchToDarkMode: "다크 모드로 전환"
    },
    "zh-TW": {
        none: "無",
        changeTheme: "變更主題",
        openThemePicker: "開啟主題選擇器",
        switchToLightMode: "切換至淺色模式",
        switchToDarkMode: "切換至深色模式"
    },
    "zh-CN": {
        none: "无",
        changeTheme: "更改主题",
        openThemePicker: "打开主题选择器",
        switchToLightMode: "切换到浅色模式",
        switchToDarkMode: "切换到深色模式"
    },
    vi: {
        none: "Không có",
        changeTheme: "Đổi giao diện",
        openThemePicker: "Mở trình chọn giao diện",
        switchToLightMode: "Chuyển sang chế độ sáng",
        switchToDarkMode: "Chuyển sang chế độ tối"
    },
    id: {
        none: "Tidak ada",
        changeTheme: "Ganti tema",
        openThemePicker: "Buka pemilih tema",
        switchToLightMode: "Beralih ke mode terang",
        switchToDarkMode: "Beralih ke mode gelap"
    },
    th: {
        none: "ไม่มี",
        changeTheme: "เปลี่ยนธีม",
        openThemePicker: "เปิดตัวเลือกธีม",
        switchToLightMode: "สลับเป็นโหมดสว่าง",
        switchToDarkMode: "สลับเป็นโหมดมืด"
    }
};

const LOCALE_ALIASES = {
    "zh": "zh-CN",
    "zh-cn": "zh-CN",
    "zh-hans": "zh-CN",
    "zh-tw": "zh-TW",
    "zh-hant": "zh-TW"
};

function getObsidianLocale(app) {
    let language = null;
    try {
        language = window.localStorage.getItem("language");
    }
    catch (_a) {
        // localStorage is normally available in Obsidian, but English remains
        // a reliable fallback in constrained environments.
    }
    if (!language) {
        try {
            // getConfig is available at runtime but is not in Obsidian's
            // public TypeScript declarations.
            language = app === null || app === void 0 ? void 0 : app.vault.getConfig("language");
        }
        catch (_b) {
            // Keep the English fallback if the legacy config lookup is absent.
        }
    }
    const normalized = String(language || "en").replace(/_/g, "-").toLowerCase();
    const locale = LOCALE_ALIASES[normalized] || normalized;
    return TRANSLATIONS[locale] ? locale : "en";
}

function translate(app, key) {
    const locale = getObsidianLocale(app);
    return TRANSLATIONS[locale][key] || TRANSLATIONS.en[key];
}

/******************************************************************************
Copyright (c) Microsoft Corporation.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
***************************************************************************** */

function __awaiter(thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
}

class ThemePickerPluginModal extends obsidian.FuzzySuggestModal {
    constructor(app) {
        super(app);
        this.DEFAULT_THEME_KEY = "";
        this.previewing = false;
        //@ts-ignore
        this.bgEl.setAttribute("style", "background-color: transparent");
        this.modalEl.classList.add("theme-picker-modal");
        //@ts-ignore
        const originalArrowUpEvent = this.scope.keys.find((key) => key.key === "ArrowUp");
        //@ts-ignore
        const originalArrowDownEvent = this.scope.keys.find((key) => key.key === "ArrowDown");
        const newFunction = function (originalFunc, modal) {
            function newCallback(e) {
                originalFunc(e, null);
                //@ts-ignore
                modal.setTheme(modal.chooser.values[modal.chooser.selectedItem].item);
                modal.previewing = true;
            }
            return newCallback;
        };
        originalArrowUpEvent.func = newFunction(originalArrowUpEvent.func, this);
        originalArrowDownEvent.func = newFunction(originalArrowDownEvent.func, this);
    }
    onOpen() {
        super.onOpen();
        //@ts-ignore
        this.initialTheme = this.getItems().find(theme => theme === this.app.customCss.theme);
        //@ts-ignore
        this.chooser.setSelectedItem(this.getItems().findIndex(theme => theme === this.app.customCss.theme));
        //@ts-ignore
        this.chooser.suggestions[this.chooser.selectedItem].scrollIntoViewIfNeeded();
    }
    onClose() {
        super.onClose();
        if (this.previewing) {
            this.setTheme(this.initialTheme);
        }
    }
    getItems() {
        //@ts-ignore
        return [this.DEFAULT_THEME_KEY, ...Object.keys(this.app.customCss.themes), ...this.app.customCss.oldThemes];
    }
    getItemText(item) {
        if (item === this.DEFAULT_THEME_KEY) {
            return translate(this.app, "none");
        }
        else {
            return item;
        }
    }
    onChooseItem(item, evt) {
        this.previewing = false;
        this.setTheme(item);
    }
    setTheme(themeName) {
        //@ts-ignore
        this.app.customCss.setTheme(themeName);
    }
}

class ThemePicker extends obsidian.Plugin {
    constructor() {
        super(...arguments);
        this.DARK_MODE_THEME_KEY = "obsidian";
        this.LIGHT_MODE_THEME_KEY = "moonstone";
        this.moonIconSvg = `<path fill="none" d="M0 0h24v24H0z"/><path d="M10 7a7 7 0 0 0 12 4.9v.1c0 5.523-4.477 10-10 10S2 17.523 2 12 6.477 2 12 2h.1A6.979 6.979 0 0 0 10 7zm-6 5a8 8 0 0 0 15.062 3.762A9 9 0 0 1 8.238 4.938 7.999 7.999 0 0 0 4 12z"/>`;
        this.sunIconSvg = `<path fill="none" d="M0 0h24v24H0z"/><path d="M12 18a6 6 0 1 1 0-12 6 6 0 0 1 0 12zm0-2a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM11 1h2v3h-2V1zm0 19h2v3h-2v-3zM3.515 4.929l1.414-1.414L7.05 5.636 5.636 7.05 3.515 4.93zM16.95 18.364l1.414-1.414 2.121 2.121-1.414 1.414-2.121-2.121zm2.121-14.85l1.414 1.415-2.121 2.121-1.414-1.414 2.121-2.121zM5.636 16.95l1.414 1.414-2.121 2.121-1.414-1.414 2.121-2.121zM23 11v2h-3v-2h3zM4 11v2H1v-2h3z"/>`;
    }
    onload() {
        return __awaiter(this, void 0, void 0, function* () {
            this.colorSchemeIcon = this.initializeColorSchemeIcon();
            const themePickerStatusBarItem = this.addStatusBarItem();
            const changeThemeButton = themePickerStatusBarItem.createDiv({
                cls: "status-bar-item mod-clickable",
                text: translate(this.app, "changeTheme")
            });
            changeThemeButton.addEventListener("click", () => {
                new ThemePickerPluginModal(this.app).open();
            });
            const changeColorSchemeButton = themePickerStatusBarItem.createDiv({
                cls: "status-bar-item mod-clickable theme-picker-color-scheme-icon",
            });
            changeColorSchemeButton.addEventListener("click", () => this.toggleColorScheme());
            changeColorSchemeButton.appendChild(this.colorSchemeIcon);
            this.changeThemeButton = changeThemeButton;
            this.changeColorSchemeButton = changeColorSchemeButton;
            this.refreshLocalizedUi();
            this.addCommand({
                id: 'open-theme-picker',
                name: translate(this.app, "openThemePicker"),
                callback: () => new ThemePickerPluginModal(this.app).open()
            });
            this.registerEvent(this.app.workspace.on("css-change", () => {
                this.colorSchemeIcon.innerHTML = this.getColorSchemeIcon();
                this.refreshLocalizedUi();
            }));
            // Obsidian refreshes its layout after a language preference change.
            // Update persistent controls so they track the app language without
            // requiring the plugin to be re-enabled.
            this.registerEvent(this.app.workspace.on("layout-change", () => {
                this.refreshLocalizedUi();
            }));
        });
    }
    initializeColorSchemeIcon() {
        const colorSchemeIcon = document.createElementNS("http://www.w3.org/2000/svg", "svg");
        colorSchemeIcon.setAttribute("viewBox", "0 0 22 22");
        colorSchemeIcon.setAttribute("width", "14");
        colorSchemeIcon.setAttribute("height", "14");
        colorSchemeIcon.innerHTML = this.getColorSchemeIcon();
        return colorSchemeIcon;
    }
    getColorSchemeIcon() {
        return this.isDarkMode() ? this.sunIconSvg : this.moonIconSvg;
    }
    toggleColorScheme() {
        let colorSchemeKey;
        if (this.isDarkMode()) {
            colorSchemeKey = this.LIGHT_MODE_THEME_KEY;
            this.colorSchemeIcon.innerHTML = this.moonIconSvg;
        }
        else {
            colorSchemeKey = this.DARK_MODE_THEME_KEY;
            this.colorSchemeIcon.innerHTML = this.sunIconSvg;
        }
        //@ts-ignore
        this.app.changeTheme(colorSchemeKey);
        this.refreshLocalizedUi();
    }
    refreshLocalizedUi() {
        var _a, _b;
        if (this.changeThemeButton) {
            this.changeThemeButton.textContent = translate(this.app, "changeTheme");
        }
        if (this.changeColorSchemeButton) {
            const label = this.isDarkMode()
                ? translate(this.app, "switchToLightMode")
                : translate(this.app, "switchToDarkMode");
            this.changeColorSchemeButton.setAttribute("aria-label", label);
            this.changeColorSchemeButton.setAttribute("title", label);
            (_a = this.changeColorSchemeButton) === null || _a === void 0 ? void 0 : _a.setAttribute("data-tooltip-position", "top");
            (_b = this.changeColorSchemeButton) === null || _b === void 0 ? void 0 : _b.setAttribute("data-tooltip-delay", "0");
        }
    }
    isDarkMode() {
        //@ts-ignore
        return this.app.vault.getConfig("theme") === this.DARK_MODE_THEME_KEY;
    }
}

module.exports = ThemePicker;


/* nosourcemap */
